[build]
  command = "npm run build"
  publish = "public"
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "max-age=0"